name: hrms_app
description: "Multi Company HRMS and Secure Attendance System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.0
  cloud_firestore: ^6.9.0
  firebase_storage: ^13.5.0
  firebase_messaging: ^16.6.0
  geolocator: ^14.0.3
  mobile_scanner: ^7.4.0
  device_info_plus: ^13.2.0
  network_info_plus: ^8.2.1
  file_picker: ^12.1.3
  excel_plus: ^2.17.0
  pdf: ^3.13.0
  path_provider: ^2.1.6
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hrms_logo.svg
