// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFZXARrPa4AyUZg7M5dYvpm37Wqv2KKU',
    appId: '1:27946741891:web:d53fb42d96c06ff003abb6',
    messagingSenderId: '27946741891',
    projectId: 'hrms-app-960b5',
    authDomain: 'hrms-app-960b5.firebaseapp.com',
    storageBucket: 'hrms-app-960b5.firebasestorage.app',
    measurementId: 'G-QX9BZQNY89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBINvSFwpz_A57vjmGsRJgSJKCy1vRx8G4',
    appId: '1:27946741891:android:af816cd9e1e41d8a03abb6',
    messagingSenderId: '27946741891',
    projectId: 'hrms-app-960b5',
    storageBucket: 'hrms-app-960b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU-zXyNnjvGEjvRtF2Twfs32V_XzKEy6A',
    appId: '1:27946741891:ios:3dc34b7d29f7d28003abb6',
    messagingSenderId: '27946741891',
    projectId: 'hrms-app-960b5',
    storageBucket: 'hrms-app-960b5.firebasestorage.app',
    iosBundleId: 'com.hrms.hrmsApp',
  );
}
