import 'package:flutter/material.dart';
import '../../app/hrms_app.dart';

class ModuleScreen extends StatefulWidget {
  final HrmsService service;
  final String title;
  final IconData icon;
  final List<String> sections;
  const ModuleScreen({super.key, required this.service, required this.title, required this.icon, required this.sections});
  @override State<ModuleScreen> createState()=>_ModuleScreenState();
}
class _ModuleScreenState extends State<ModuleScreen>{
  final Map<String,List<Map<String,String>>> data={};
  void add(String section){final c=TextEditingController();showDialog(context:context,builder:(_)=>AlertDialog(title:Text('Add $section'),content:TextField(controller:c,decoration:InputDecoration(labelText:section,hintText:'Enter details',border:const OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:(){if(c.text.trim().isNotEmpty)setState(()=>(data[section]??=[]).add({'title':c.text.trim(),'details':'Created • Pending approval'}));Navigator.pop(context);},child:const Text('Save'))]));}
  @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[Row(children:[CircleAvatar(radius:25,child:Icon(widget.icon)),const SizedBox(width:12),Expanded(child:Text(widget.title,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800))) ]),const SizedBox(height:18),for(final section in widget.sections)...[_card(section),const SizedBox(height:12)]]);
  Widget _card(String section){final rows=data[section]??[];return Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(section,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800))),FilledButton.icon(onPressed:()=>add(section),icon:const Icon(Icons.add),label:const Text('Add'))]),if(rows.isEmpty)const Padding(padding:EdgeInsets.only(top:14),child:Text('No records yet.')) else ...rows.map((r)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.description_outlined),title:Text(r['title']!),subtitle:Text(r['details']!),trailing:const Icon(Icons.chevron_right))) ])));}
}

class DashboardScreen extends ModuleScreen { DashboardScreen({super.key,required HrmsService service}):super(service:service,title:'Dashboard',icon:Icons.dashboard,sections:const ['Attendance Summary','Employee Summary','Pending Requests','Upcoming Holidays','Birthdays','Work Anniversaries','New Joiners','HR Analytics']); }
class EmployeeScreen extends ModuleScreen { EmployeeScreen({super.key,required HrmsService service}):super(service:service,title:'Employee Management',icon:Icons.people,sections:const ['Employee List','Add Employee','Employee Profile','Personal Details','Contact Details','Emergency Contact','Address','Department & Designation','Reporting Manager','Joining & Employment','Bank Details','Documents','Skills','Education','Experience']); }
class LifecycleScreen extends ModuleScreen { LifecycleScreen({super.key,required HrmsService service}):super(service:service,title:'Employee Lifecycle',icon:Icons.timeline,sections:const ['Recruitment','Candidate Management','Interview','Selection','Offer Letter','Joining','Onboarding','Probation','Confirmation','Transfer','Promotion','Increment','Resignation','Exit','Full & Final Settlement','Relieving Letter','Experience Letter']); }
class AttendanceScreen extends ModuleScreen { AttendanceScreen({super.key,required HrmsService service}):super(service:service,title:'Attendance',icon:Icons.access_time,sections:const ['Daily Attendance','Punch In / Punch Out','Working Hours','Break Management','Attendance Rules','Attendance Types','Attendance History','Attendance Correction','Correction Approval','Attendance Reports']); }
class LeaveScreen extends ModuleScreen { LeaveScreen({super.key,required HrmsService service}):super(service:service,title:'Leave Management',icon:Icons.event_available,sections:const ['Leave Types','Leave Balance','Apply Leave','Cancel Leave','Approve Leave','Reject Leave','Leave History','Leave Calendar','Holiday Calendar','Leave Rules']); }
class PayrollScreen extends ModuleScreen { PayrollScreen({super.key,required HrmsService service}):super(service:service,title:'Payroll',icon:Icons.payments,sections:const ['Salary Structure','Basic Salary','Allowances','Bonuses','Incentives','Deductions','PF','ESI','Professional Tax','TDS','Overtime','Salary Calculation','Payroll Processing','Payslip','Salary History','Bank Transfer Data','Full & Final Settlement']); }
class DepartmentScreen extends ModuleScreen { DepartmentScreen({super.key,required HrmsService service}):super(service:service,title:'Department & Organization',icon:Icons.account_tree,sections:const ['Departments','Designations','Teams','Reporting Structure','Managers','Organization Chart','Branches','Locations']); }
class ShiftScreen extends ModuleScreen { ShiftScreen({super.key,required HrmsService service}):super(service:service,title:'Shift & Roster',icon:Icons.schedule,sections:const ['Create Shift','Assign Shift','Shift Timing','Multiple Shifts','Night Shift','Rotational Shift','Weekly Roster','Employee Roster','Shift Change Request']); }
class PerformanceScreen extends ModuleScreen { PerformanceScreen({super.key,required HrmsService service}):super(service:service,title:'Performance Management',icon:Icons.insights,sections:const ['Goals','KPI','Performance Review','Self Assessment','Manager Assessment','Rating','Appraisal','Promotion','Increment','Performance History']); }
class DocumentsScreen extends ModuleScreen { DocumentsScreen({super.key,required HrmsService service}):super(service:service,title:'Document Management',icon:Icons.folder,sections:const ['Employee Documents','Company Documents','Offer Letter','Appointment Letter','Joining Letter','Salary Slip','Increment Letter','Promotion Letter','Experience Letter','Relieving Letter','Document Verification','Document Expiry Alerts']); }
class RecruitmentScreen extends ModuleScreen { RecruitmentScreen({super.key,required HrmsService service}):super(service:service,title:'Recruitment',icon:Icons.work,sections:const ['Job Openings','Applications','Candidate Profiles','Resume','Interview','Interview Feedback','Shortlist','Selection','Rejection','Offer Management']); }
class EssScreen extends ModuleScreen { EssScreen({super.key,required HrmsService service}):super(service:service,title:'Employee Self Service',icon:Icons.person,sections:const ['My Profile','My Attendance','My Punch In/Out','My Leave','My Leave Balance','My Payslip','My Documents','My Requests','My Performance','My Assets','Company Announcements']); }
class ExpenseScreen extends ModuleScreen { ExpenseScreen({super.key,required HrmsService service}):super(service:service,title:'Expense Management',icon:Icons.receipt_long,sections:const ['Expense Claim','Travel Expense','Food Expense','Other Expense','Bill Upload','Approval','Rejection','Reimbursement','Expense History']); }
class AssetsScreen extends ModuleScreen { AssetsScreen({super.key,required HrmsService service}):super(service:service,title:'Asset Management',icon:Icons.devices,sections:const ['Laptop','Desktop','Mobile','ID Card','SIM','Accessories','Asset Assignment','Asset Return','Asset History']); }
class NotificationsScreen extends ModuleScreen { NotificationsScreen({super.key,required HrmsService service}):super(service:service,title:'Notifications',icon:Icons.notifications,sections:const ['Push Notifications','Leave Notification','Attendance Notification','Late Notification','Punch Reminder','Missing Punch Alert','Payroll Notification','Announcement','Birthday','Work Anniversary']); }
class CommunicationScreen extends ModuleScreen { CommunicationScreen({super.key,required HrmsService service}):super(service:service,title:'Company Communication',icon:Icons.campaign,sections:const ['Announcements','Notices','Circulars','Company Events','Holiday Announcement','Important Updates']); }
class ReportsScreen extends ModuleScreen { ReportsScreen({super.key,required HrmsService service}):super(service:service,title:'Reports & Analytics',icon:Icons.analytics,sections:const ['Employee Report','Attendance Report','Leave Report','Payroll Report','Overtime Report','Performance Report','Recruitment Report','Expense Report','Asset Report','Department Report','Monthly HR Report','PDF Export','Excel Export']); }
class AdminScreen extends ModuleScreen { AdminScreen({super.key,required HrmsService service}):super(service:service,title:'Admin & Security',icon:Icons.security,sections:const ['Super Admin','HR Admin','Manager','Employee','Roles','Permissions','Access Control','Login','OTP','Password','Session Management','Audit Logs','Activity Logs','Data Backup']); }
class SettingsScreen extends ModuleScreen { SettingsScreen({super.key,required HrmsService service}):super(service:service,title:'Company Settings',icon:Icons.settings,sections:const ['Company Profile','Branches','Departments','Designations','Working Days','Holidays','Leave Rules','Attendance Rules','Shift Rules','Payroll Rules','Notification Settings','Approval Workflow']); }
class AdvancedAttendanceScreen extends ModuleScreen { AdvancedAttendanceScreen({super.key,required HrmsService service}):super(service:service,title:'Advanced Attendance',icon:Icons.gps_fixed,sections:const ['GPS Attendance','Geofencing','Office Location','Multiple Office Locations','IP Restriction','Device Restriction','Selfie / Face Verification','QR Attendance','Biometric Integration','Remote / WFH','On-Duty','Attendance Approval']); }
