import 'package:flutter/material.dart';
import '../../app/hrms_app.dart';

class ModuleScreen extends StatefulWidget {
  final HrmsService service; final String title; final IconData icon; final List<String> sections;
  const ModuleScreen({super.key,required this.service,required this.title,required this.icon,required this.sections});
  @override State<ModuleScreen> createState()=>_ModuleScreenState();
}
class _ModuleScreenState extends State<ModuleScreen>{
  final Map<String,List<String>> records={};
  void addRecord(String section){final c1=TextEditingController(),c2=TextEditingController(),c3=TextEditingController();showDialog(context:context,builder:(_)=>AlertDialog(title:Text('Add $section'),content:SingleChildScrollView(child:Column(children:[TextField(controller:c1,decoration:const InputDecoration(labelText:'Name / Title',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:c2,decoration:const InputDecoration(labelText:'Details / Description',border:OutlineInputBorder()),maxLines:2),const SizedBox(height:12),TextField(controller:c3,decoration:const InputDecoration(labelText:'Status / Amount / Date',border:OutlineInputBorder()))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:(){if(c1.text.trim().isEmpty)return;records.putIfAbsent(section,()=>[]).add('${c1.text.trim()} — ${c2.text.trim()} — ${c3.text.trim()}');Navigator.pop(context);setState((){});},child:const Text('Save'))]));}
  void remove(String section,int i){records[section]!.removeAt(i);setState((){});}
  @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[Row(children:[CircleAvatar(radius:26,child:Icon(widget.icon)),const SizedBox(width:12),Expanded(child:Text(widget.title,style:const TextStyle(fontSize:27,fontWeight:FontWeight.w800)))]),const SizedBox(height:8),Text('${widget.sections.length} features • Add and manage records below'),const SizedBox(height:18),...widget.sections.map((s){final list=records[s]??[];return Card(margin:const EdgeInsets.only(bottom:12),child:ExpansionTile(leading:Icon(widget.icon),title:Text(s,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${list.length} record(s)'),children:[Padding(padding:const EdgeInsets.fromLTRB(16,0,16,12),child:Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:()=>addRecord(s),icon:const Icon(Icons.add),label:const Text('Add Record')))),...list.asMap().entries.map((e)=>ListTile(title:Text(e.value),leading:const Icon(Icons.check_circle_outline),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>remove(s,e.key))))]));})]);
}

class DashboardScreen extends StatelessWidget { final HrmsService service; const DashboardScreen({super.key,required this.service}); @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Dashboard',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:6),Text('Today • ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}'),const SizedBox(height:18),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.6,children:[_stat('Employees',service.employees.length,Icons.people),_stat('Present',service.present,Icons.check_circle),_stat('Absent',service.employees.length-service.present-service.late-service.onLeave,Icons.person_off),_stat('Late',service.late,Icons.schedule),_stat('Early Exit',service.earlyExit,Icons.logout),_stat('WFH',service.wfh,Icons.home_work),_stat('On Leave',service.onLeave,Icons.event_busy),_stat('Pending Leave',service.pendingLeaves,Icons.pending_actions)]),const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Attendance Summary',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:12),Text('Present: ${service.present}'),Text('Late: ${service.late}'),Text('WFH: ${service.wfh}'),Text('On Leave: ${service.onLeave}'),Text('Pending Leave: ${service.pendingLeaves}')])))]);
  Widget _stat(String t,int n,IconData i)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[Icon(i,size:28),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text('$n',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w800)),Text(t)]))])));
}

class EmployeeScreen extends StatefulWidget { final HrmsService service; const EmployeeScreen({super.key,required this.service}); @override State<EmployeeScreen> createState()=>_EmployeeScreenState(); }
class _EmployeeScreenState extends State<EmployeeScreen>{
 void add(){final n=TextEditingController(),d=TextEditingController(),des=TextEditingController(),p=TextEditingController(),e=TextEditingController();showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Add Employee'),content:SingleChildScrollView(child:Column(children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Full Name *')),TextField(controller:d,decoration:const InputDecoration(labelText:'Department')),TextField(controller:des,decoration:const InputDecoration(labelText:'Designation')),TextField(controller:p,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Phone')),TextField(controller:e,decoration:const InputDecoration(labelText:'Email'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:(){if(n.text.trim().isEmpty)return;final id='EMP${(service.employees.length+1).toString().padLeft(3,'0')}';service.addEmployee(Employee(id:id,name:n.text.trim(),department:d.text.trim(),designation:des.text.trim().isEmpty?'Employee':des.text.trim(),manager:'HR Admin',joiningDate:DateTime.now(),employmentType:'Full Time',status:'Active',phone:p.text.trim(),email:e.text.trim()));Navigator.pop(context);setState((){});},child:const Text('Save'))]));}
 @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[Row(children:[const Expanded(child:Text('Employee Management',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800))),FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('Add'))]),const SizedBox(height:16),...service.employees.map((e)=>Card(child:ListTile(leading:CircleAvatar(child:Text(e.name[0])),title:Text(e.name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${e.id} • ${e.department}\n${e.designation} • ${e.phone}\n${e.email}'),isThreeLine:true,trailing:PopupMenuButton<String>(onSelected:(v){if(v=='delete'){service.removeEmployee(e.id);setState((){});}},itemBuilder:(_)=>const[PopupMenuItem(value:'delete',child:Text('Delete'))]))))]);
}

class AttendanceScreen extends StatefulWidget { final HrmsService service; const AttendanceScreen({super.key,required this.service}); @override State<AttendanceScreen> createState()=>_AttendanceScreenState(); }
class _AttendanceScreenState extends State<AttendanceScreen>{ String employee='EMP001'; @override Widget build(BuildContext context){if(!service.employees.any((e)=>e.id==employee))employee=service.employees.first.id;final r=service.todayFor(employee);return ListView(padding:const EdgeInsets.all(16),children:[const Text('Attendance',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:16),DropdownButtonFormField<String>(value:employee,decoration:const InputDecoration(labelText:'Employee',border:OutlineInputBorder()),items:service.employees.map((e)=>DropdownMenuItem(value:e.id,child:Text('${e.name} (${e.id})'))).toList(),onChanged:(v)=>setState(()=>employee=v!)),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[Text(r?.punchIn==null?'Not punched in':'Punched in: ${_time(r!.punchIn!)}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w700)),if(r?.punchOut!=null)Text('Punched out: ${_time(r!.punchOut!)}'),const SizedBox(height:16),Row(children:[Expanded(child:FilledButton.icon(onPressed:r?.punchIn==null?(){service.punchIn(employee);setState((){});}:null,icon:const Icon(Icons.login),label:const Text('Punch In'))),const SizedBox(width:10),Expanded(child:OutlinedButton.icon(onPressed:r?.punchIn!=null&&r?.punchOut==null?(){service.punchOut(employee);setState((){});}:null,icon:const Icon(Icons.logout),label:const Text('Punch Out')))]),if(r!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text('Status: ${r.status} • Working ${r.workingTime.inHours}h ${r.workingTime.inMinutes%60}m • OT ${r.overtime.inHours}h ${r.overtime.inMinutes%60}m'))])),const SizedBox(height:12),Card(child:ListTile(title:const Text('Attendance History'),subtitle:Text('${service.attendance.length} attendance record(s)')))]);}
 String _time(DateTime d)=>'${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';
}

class LeaveScreen extends StatefulWidget { final HrmsService service; const LeaveScreen({super.key,required this.service}); @override State<LeaveScreen> createState()=>_LeaveScreenState(); }
class _LeaveScreenState extends State<LeaveScreen>{
 void apply(){String emp=service.employees.first.id,type='Casual Leave';DateTime from=DateTime.now(),to=DateTime.now();final reason=TextEditingController();showDialog(context:context,builder:(_)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Apply Leave'),content:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<String>(value:emp,decoration:const InputDecoration(labelText:'Employee'),items:service.employees.map((e)=>DropdownMenuItem(value:e.id,child:Text(e.name))).toList(),onChanged:(v)=>set(()=>emp=v!)),DropdownButtonFormField<String>(value:type,decoration:const InputDecoration(labelText:'Leave Type'),items:const['Casual Leave','Sick Leave','Earned Leave','Unpaid Leave'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>set(()=>type=v!)),ListTile(leading:const Icon(Icons.date_range),title:Text('From ${from.day}/${from.month}/${from.year}'),onTap:()async{final x=await showDatePicker(context:c,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:365)),initialDate:from);if(x!=null)set(()=>from=x);}),ListTile(leading:const Icon(Icons.event),title:Text('To ${to.day}/${to.month}/${to.year}'),onTap:()async{final x=await showDatePicker(context:c,firstDate:from,lastDate:DateTime.now().add(const Duration(days:365)),initialDate:to.isBefore(from)?from:to);if(x!=null)set(()=>to=x);}),TextField(controller:reason,decoration:const InputDecoration(labelText:'Reason',border:OutlineInputBorder()),maxLines:2)])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:(){if(reason.text.trim().isEmpty||to.isBefore(from))return;service.applyLeave(LeaveRequest(id:'L${service.leaves.length+1}',employeeId:emp,type:type,from:from,to:to,reason:reason.text.trim()));Navigator.pop(c);setState((){});},child:const Text('Submit'))]));}
 @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[Row(children:[const Expanded(child:Text('Leave Management',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800))),FilledButton.icon(onPressed:apply,icon:const Icon(Icons.add),label:const Text('Apply'))]),const SizedBox(height:16),...service.employees.map((e)=>Card(child:ListTile(title:Text(e.name),subtitle:Text('Balance: ${service.leaveBalances[e.id]??0} days • Requests: ${service.leaves.where((l)=>l.employeeId==e.id).length}')))),const SizedBox(height:8),...service.leaves.map((l)=>Card(child:ListTile(title:Text('${l.type} • ${l.days} day(s)'),subtitle:Text('${l.employeeId} • ${l.reason}'),trailing:Chip(label:Text(l.status)),onTap:()=>showDialog(context:context,builder:(_)=>AlertDialog(title:Text(l.type),content:Text('Status: ${l.status}\n${l.from.day}/${l.from.month}/${l.from.year} → ${l.to.day}/${l.to.month}/${l.to.year}\nReason: ${l.reason}'),actions:[if(l.status=='Pending')TextButton(onPressed:(){service.decideLeave(l.id,false);Navigator.pop(context);setState((){});},child:const Text('Reject')),if(l.status=='Pending')FilledButton(onPressed:(){service.decideLeave(l.id,true);Navigator.pop(context);setState((){});},child:const Text('Approve')),TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]))))];
}

class LifecycleScreen extends ModuleScreen { LifecycleScreen({super.key,required HrmsService service}):super(service:service,title:'Employee Lifecycle',icon:Icons.timeline,sections:const ['Recruitment','Candidate Management','Interview','Selection','Offer Letter','Joining','Onboarding','Probation','Confirmation','Transfer','Promotion','Increment','Resignation','Exit','Full & Final Settlement','Relieving Letter','Experience Letter']); }
class PayrollScreen extends ModuleScreen { PayrollScreen({super.key,required HrmsService service}):super(service:service,title:'Payroll',icon:Icons.payments,sections:const ['Salary Structure','Basic Salary','Allowances','Bonuses','Incentives','Deductions','PF','ESI','Professional Tax','TDS','Overtime','Salary Calculation','Payroll Processing','Payslip','Salary History','Bank Transfer Data','Full & Final Settlement']); }
class DepartmentScreen extends ModuleScreen { DepartmentScreen({super.key,required HrmsService service}):super(service:service,title:'Department & Organization',icon:Icons.account_tree,sections:const ['Departments','Designations','Teams','Reporting Structure','Managers','Organization Chart','Branches','Locations']); }
class ShiftScreen extends ModuleScreen { ShiftScreen({super.key,required HrmsService service}):super(service:service,title:'Shift & Roster',icon:Icons.schedule,sections:const ['Create Shift','Assign Shift','Shift Timing','Multiple Shifts','Night Shift','Rotational Shift','Weekly Roster','Employee Roster','Shift Change Request']); }
class PerformanceScreen extends ModuleScreen { PerformanceScreen({super.key,required HrmsService service}):super(service:service,title:'Performance Management',icon:Icons.insights,sections:const ['Goals','KPI','Performance Review','Self Assessment','Manager Assessment','Rating','Appraisal','Promotion','Increment','Performance History']); }
class DocumentsScreen extends ModuleScreen { DocumentsScreen({super.key,required HrmsService service}):super(service:service,title:'Document Management',icon:Icons.folder,sections:const ['Employee Documents','Company Documents','Offer Letter','Appointment Letter','Joining Letter','Salary Slip','Increment Letter','Promotion Letter','Experience Letter','Relieving Letter','Document Verification','Document Expiry Alerts']); }
class RecruitmentScreen extends ModuleScreen { RecruitmentScreen({super.key,required HrmsService service}):super(service:service,title:'Recruitment',icon:Icons.work,sections:const ['Job Openings','Applications','Candidate Profiles','Resume','Interview','Interview Feedback','Shortlist','Selection','Rejection','Offer Management']); }
class EssScreen extends ModuleScreen { EssScreen({super.key,required HrmsService service}):super(service:service,title:'Employee Self Service',icon:Icons.person,sections:const ['My Profile','My Attendance','My Punch In/Out','My Leave','My Leave Balance','My Payslip','My Documents','My Requests','My Performance','My Assets','Company Announcements']); }
class ExpenseScreen extends ModuleScreen { ExpenseScreen({super.key,required HrmsService service}):super(service:service,title:'Expense Management',icon:Icons.receipt_long,sections:const ['Expense Claim','Travel Expense','Food Expense','Other Expense','Bill Upload','Approval','Rejection','Reimbursement','Expense History']); }
class AssetsScreen extends ModuleScreen { AssetsScreen({super.key,required HrmsService service}):super(service:service,title:'Asset Management',icon:Icons.devices,sections:const ['Laptop','Desktop','Mobile','ID Card','SIM','Accessories','Asset Assignment','Asset Return','Asset History']); }
class NotificationsScreen extends ModuleScreen { NotificationsScreen({super.key,required HrmsService service}):super(service:service,title:'Notifications',icon:Icons.notifications,sections:const ['Push Notifications','Leave Notification','Attendance Notification','Late Notification','Punch Reminder','Missing Punch Alert','Payroll Notification','Announcement','Birthday','Work Anniversary']); }
class CommunicationScreen extends ModuleScreen { CommunicationScreen({super.key,required HrmsService service}):super(service:service,title:'Company Communication',icon:Icons.campaign,sections:const ['Announcements','Notices','Circulars','Company Events','Holiday Announcement','Important Updates']); }
class ReportsScreen extends ModuleScreen { ReportsScreen({super.key,required HrmsService service}):super(service:service,title:'Reports & Analytics',icon:Icons.analytics,sections:const ['Employee Report','Attendance Report','Leave Report','Payroll Report','Overtime Report','Performance Report','Recruitment Report','Expense Report','Asset Report','Department Report','Monthly HR Report','PDF Export','Excel Export']); }
class AdminScreen extends ModuleScreen { AdminScreen({super.key,required HrmsService service}):super(service:service,title:'Admin & Security',icon:Icons.security,sections:const ['Super Admin','HR Admin','Manager','Employee','Roles','Permissions','Access Control','Login','OTP','Password','Session Management','Audit Logs','Activity Logs','Data Backup']); }
class SettingsScreen extends ModuleScreen { SettingsScreen({super.key,required HrmsService service}):super(service:service,title:'Company Settings',icon:Icons.settings,sections:const ['Company Profile','Branches','Departments','Designations','Working Days','Holidays','Leave Rules','Attendance Rules','Shift Rules','Payroll Rules','Notification Settings','Approval Workflow']); }
class AdvancedAttendanceScreen extends ModuleScreen { AdvancedAttendanceScreen({super.key,required HrmsService service}):super(service:service,title:'Advanced Attendance',icon:Icons.gps_fixed,sections:const ['GPS Attendance','Geofencing','Office Location','Multiple Office Locations','IP Restriction','Device Restriction','Selfie / Face Verification','QR Attendance','Biometric Integration','Remote / WFH','On-Duty','Attendance Approval']); }
